version: "3.8"

networks:
  default:

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "8080:8080"
    volumes:
    - ./frontend/src:/app/src
    - /node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_USERNAME=admin
      - DB_PASSWORD=password
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=sqa
      - PORT=3000
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - default
    environment:
      - NODE_ENV=production
      - OLLAMA_DIR=/root/.ollama
      - OLLAMA_NUM_THREADS=8
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_MODEL_DISK_CACHE=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /mnt/c/Users/<username>/.ollama/models:/root/.ollama/models

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      
volumes:
  mongo_data:
    driver: local
